services:
  postgres:
    image: postgres:16.2
    container_name: postgresdb
#    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
#    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=develop@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=develop
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json